version: '3.8'
services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
  backend:
    build:
      context: ..
      dockerfile: pokemon-dist/Dockerfile.backend
    container_name: pokemon-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - POKEAPI_URL=https://pokeapi.co/api/v2/pokemon
    depends_on:
      redis:
        condition: service_healthy
  frontend:
    build:
      context: ..
      dockerfile: pokemon-dist/Dockerfile.frontend
    container_name: pokemon-frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://backend:8080
    depends_on:
      - backend 