# Dockerfile para backend
FROM eclipse-temurin:17-jdk as build
WORKDIR /app
COPY pokemon-api .
RUN chmod +x gradlew
RUN ./gradlew build -x test

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/build/libs/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-Djava.net.preferIPv4Stack=true", "-jar", "app.jar"] 